In [4]:
import numpy as np

In [5]:
lista=list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [6]:
arreglo = np.array (lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
type (arreglo)

numpy.ndarray

In [8]:
arreglo.dtype

dtype('int32')

In [9]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [10]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [11]:
arreglonuevo= np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arreglonuevo2= np.arange(1,11,2)
arreglonuevo2

array([1, 3, 5, 7, 9])

In [13]:
promedio= np.mean(arreglo)
promedio

5.5

In [14]:
mediana= np.median(arreglo)
mediana

5.5

In [15]:
desviacion_std= np.std(arreglo)
desviacion_std

2.8722813232690143

In [16]:
arreglos_de_unos= np.ones(10)
arreglos_de_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
arreglos_de_zero= np.zeros(10)
arreglos_de_zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
arreglo_int_ones= arreglos_de_unos.astype(int)
arreglo_int_ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [19]:
arreglo_aleatorio= np.random.rand(5)
arreglo_aleatorio

array([0.10676111, 0.93358504, 0.49517494, 0.44368565, 0.50988949])

In [20]:
matriz= np.random.rand(3,3)
matriz

array([[0.28019575, 0.82954799, 0.08708261],
       [0.34787327, 0.22941183, 0.12444484],
       [0.50702204, 0.43165177, 0.67598433]])

In [21]:
arreglo_aleatorio2= np.random.randint(1,100,10)
arreglo_aleatorio2

array([73, 81, 94, 98, 60,  6, 78, 41, 81,  5])

In [22]:
matriz2= np.random.randint(1,100,(15,15))
matriz2

array([[69, 65, 46, 45, 40,  5, 24, 44, 29, 30, 19, 27, 55, 68,  3],
       [98, 89, 98, 89, 53, 29, 34,  2, 72,  3,  4, 66, 28, 63, 12],
       [85, 10,  2, 19,  1, 86, 75, 46, 16, 84, 34, 29, 21, 85, 27],
       [86, 46, 72, 14, 38, 34, 64, 51,  7, 27, 18, 62, 63,  9,  1],
       [72, 48, 58, 52, 69, 86, 91, 85, 87, 75, 71, 21, 44, 10, 89],
       [48, 99, 56, 59, 30,  2, 58, 58, 99, 20, 22, 22, 13, 27, 96],
       [95, 81, 64, 11,  8, 70, 64,  3,  9, 99, 87, 83, 34, 62, 13],
       [96, 93, 55, 54, 25, 69, 22, 72, 24, 43, 71, 40, 81, 83, 14],
       [75, 16,  6, 11, 29, 93, 96, 83, 60, 24, 44, 27, 47, 78, 27],
       [94, 49, 45, 90, 95,  7, 34, 97, 82, 81, 99, 85, 37, 97, 94],
       [43, 23, 60, 13, 29, 41, 56,  6, 86, 26, 98, 90, 50, 18, 44],
       [49, 64, 65, 44, 67, 98, 15, 26,  7,  5, 38, 55, 62, 38, 11],
       [20, 63,  4, 27, 95, 11, 93, 61, 23, 61, 76, 81, 65, 13, 84],
       [35, 84, 74, 27, 65, 26, 14, 79, 95, 61, 40, 80, 93, 81, 72],
       [ 8, 56,  1, 45, 92, 28, 25